var displayNames =
      {
      "status" : "Status:",
      "firstName" : "First Name:",
      "middleName" : "Middle Name:",
      "lastName" : "Last Name:",
      "alias" : "Alias:",
      "ageLastSeen" : "Age Last Seen:",
      "ageNow" : "Age Now:",
      "race" : "Race:",
      "ethnicity" : "Ethnicity:",
      "sex" : "Sex:",
      "height" : "Height:",
      "heightUnits" : "Height Units:",
      "weight" : "Weight:",
      "weightUnits" : "Weight Units:",

      "dateLastSeen" : "Date Last Seen:",
      "dateEntered" : "Date Entered:",
      "city" : "City:",
      "state" : "State:",
      "zipCode" : "Zipcode:",
      "county" : "County:",

      "vehicleMake" : "Vehicle Make:",
      "vehicleModel" : "Vehicle Model:",
      "year" : "Year:",
      "style" : "Style",
      "vehicleColor" : "Vehicle Color:",
      "tagType" : "Tag Type:",
      "tagNumber" : "Tag Number:",
      "tagState" : "Tag State:",
      "expYear" : "Expiration Year:",
      "vehicleComments" : "Vehicle Comments:",
      "airline" : "Airline:",
      "bus" : "Bus:",

      "clothingAccesories" : "Clothing Accesories:",
      "clothing" : "Clothing:",
      "footwear" : "Footwear:",
      "jewelry" : "Jewelry:",
      "eyewear" : "Eyewear:",
      "accesories" : "Accesories:",

      "title" : "Title:",
      "detFirstName" : "Detective First Name:",
      "detLastName" : "Detective Last Name:",
      "phone" : "Phone:",
      "website" : "Website:",
      "caseNumber" : "Case Number:",
      "dateReported" : "Date Reported:",
      "jurisdiction" : "Jurisdiction:",
      "agency" : "Agency:",
      "addressOne" : "Address Line One:",
      "addressTwo" : "Address Line Two:",
      "detCity" : "Detective City:",
      "detState" : "Detective State:",
      "detZipCode" : "Detective Zip Code:",
      "comments" : "Comments:",

      "noDistinctiveFeatures" : "Distinctive Features?:",
      "hairColor" : "Hair Color:",
      "headHair" : "Head Hair:",
      "bodyHair" : "Body Hair:",
      "facialHair" : "Facial Hair:",
      "leftEyeColor" : "Left Eye Color:",
      "rightEyeColor" : "Right Eye Color:",
      "eyeDescription" : "Eye Description:",
      "scars" : "Scars:",
      "tattoos" : "Tattoos:",
      "piercings" : "Piercings:",
      "fingerNails" : "Fingernails:",
      "other" : "Other:",

      "amputations" : "Amputations:",
      "deformalities" : "Deformalities:",
      "artificialParts" : "Artificial Parts:",
      "foreignObjects" : "Foreign Objects:",
      "skeletalInfo" : "Skeletal Info:"
    };
